/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxrpc.samples.jsr109pojo;


public class  JaxRpcTestService_echoSimpleUserType_RequestStruct
{

protected java.lang.String String_1;

protected org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType SimpleUserType_2;
public JaxRpcTestService_echoSimpleUserType_RequestStruct(){}

public JaxRpcTestService_echoSimpleUserType_RequestStruct(java.lang.String String_1,org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType SimpleUserType_2){
this.String_1=String_1;
this.SimpleUserType_2=SimpleUserType_2;
}
public java.lang.String getString_1() { return String_1 ;}

public void setString_1(java.lang.String myvar ){  String_1=myvar ;}

public org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType getSimpleUserType_2() { return SimpleUserType_2 ;}

public void setSimpleUserType_2(org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType myvar ){  SimpleUserType_2=myvar ;}

}
