<?xml version="1.0" encoding="UTF-8"?>

<definitions name="EndpointService" targetNamespace="http://org.jboss.ws/jaxws/jbws3223" xmlns:tns="http://org.jboss.ws/jaxws/jbws3223" 
  xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types/>
  <message name="EndpointInterface_echo">
    <part name="String_1" type="xsd:string"/>
  </message>
  <message name="EndpointInterface_echoResponse">
    <part name="result" type="xsd:string"/>
  </message>
  <portType name="EndpointInterface">
    <operation name="echo" parameterOrder="String_1">
      <input message="tns:EndpointInterface_echo"/>
      <output message="tns:EndpointInterface_echoResponse"/>
    </operation>
  </portType>
  <binding name="EndpointInterfaceBinding" type="tns:EndpointInterface">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="echo">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://org.jboss.ws/jaxws/jbws3223"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://org.jboss.ws/jaxws/jbws3223"/>
      </output>
    </operation>
  </binding>
  <service name="EndpointService">
    <port name="EndpointInterfacePort" binding="tns:EndpointInterfaceBinding">
      <soap:address location="http://@jboss.bind.address@:@add_int(port-offset.shared-tests.jboss,8080)@/jaxws-jbws3223"/>
    </port>
  </service>
</definitions>
