/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxrpc.samples.jsr109ejb;


public class  JaxRpcTestService_echoString_RequestStruct
{

protected java.lang.String String_1;

protected java.lang.String String_2;
public JaxRpcTestService_echoString_RequestStruct(){}

public JaxRpcTestService_echoString_RequestStruct(java.lang.String String_1,java.lang.String String_2){
this.String_1=String_1;
this.String_2=String_2;
}
public java.lang.String getString_1() { return String_1 ;}

public void setString_1(java.lang.String myvar ){  String_1=myvar ;}

public java.lang.String getString_2() { return String_2 ;}

public void setString_2(java.lang.String myvar ){  String_2=myvar ;}

}
