
package org.jboss.test.ws.jaxws.jbws2937;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Endpoint", targetNamespace = "http://jboss.org/jbws2937")
public interface Endpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.jboss.test.ws.jaxws.jbws2937.UserType
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://jboss.org/jbws2937", className = "org.jboss.test.ws.jaxws.jbws2937.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://jboss.org/jbws2937", className = "org.jboss.test.ws.jaxws.jbws2937.EchoResponse")
    public UserType echo(
        @WebParam(name = "arg0", targetNamespace = "")
        UserType arg0);

}
