/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jboss.test.ws.jaxws.jbws2937;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Endpoint", targetNamespace = "http://jboss.org/jbws2937")
public interface Endpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.jboss.test.ws.jaxws.jbws2937.UserType
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://jboss.org/jbws2937", className = "org.jboss.test.ws.jaxws.jbws2937.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://jboss.org/jbws2937", className = "org.jboss.test.ws.jaxws.jbws2937.EchoResponse")
    public UserType echo(
        @WebParam(name = "arg0", targetNamespace = "")
        UserType arg0);

}
