/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jboss.test.ws.jaxws.jbws2278;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 *
 */
@WebFault(name = "TestException", targetNamespace = "http://org.jboss.test.ws/jbws2278/types")
public class TestException_Exception
    extends Exception
{

   private static final long serialVersionUID = -2525142372579037232L;
   /**
    * Java type that goes as soapenv:Fault detail element.
    *
    */
   private final TestException faultInfo;

   /**
    *
    * @param faultInfo
    * @param message
    */
   public TestException_Exception(String message, TestException faultInfo) {
      super(message);
      this.faultInfo = faultInfo;
   }

   /**
    *
    * @param faultInfo
    * @param message
    * @param cause
    */
   public TestException_Exception(String message, TestException faultInfo, Throwable cause) {
      super(message, cause);
      this.faultInfo = faultInfo;
   }

   /**
    *
    * @return
    *     returns fault bean: org.jboss.test.ws.jaxws.jbws2234.TestException
    */
   public TestException getFaultInfo() {
      return faultInfo;
   }

}
