/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.jboss.test.ws.jaxws.jbws2278;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 *
 */
@WebFault(name = "TestException", targetNamespace = "http://org.jboss.test.ws/jbws2278/types")
public class TestException_Exception
    extends Exception
{

   private static final long serialVersionUID = -2525142372579037232L;
   /**
    * Java type that goes as soapenv:Fault detail element.
    *
    */
   private final TestException faultInfo;

   /**
    *
    * @param faultInfo
    * @param message
    */
   public TestException_Exception(String message, TestException faultInfo) {
      super(message);
      this.faultInfo = faultInfo;
   }

   /**
    *
    * @param faultInfo
    * @param message
    * @param cause
    */
   public TestException_Exception(String message, TestException faultInfo, Throwable cause) {
      super(message, cause);
      this.faultInfo = faultInfo;
   }

   /**
    *
    * @return
    *     returns fault bean: org.jboss.test.ws.jaxws.jbws2234.TestException
    */
   public TestException getFaultInfo() {
      return faultInfo;
   }

}
