<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://org.jboss.ws.jaxws.cxf/wsrm" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RMService"
  targetNamespace="http://org.jboss.ws.jaxws.cxf/wsrm">
  
  <wsp:Policy wsu:Id="RM" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
    <wsam:Addressing xmlns:wsam="http://www.w3.org/2007/02/addressing/metadata">
      <wsp:Policy/>
    </wsam:Addressing>
    <wsrmp:RMAssertion xmlns:wsrmp="http://schemas.xmlsoap.org/ws/2005/02/rm/policy">
      <wsrmp:BaseRetransmissionInterval Milliseconds="10000"/>
    </wsrmp:RMAssertion>
  </wsp:Policy>
  
  <wsdl:message name="echoResponse">
    <wsdl:part name="return" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="echo">
    <wsdl:part name="arg0" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RMEndpoint">
    <wsdl:operation name="echo">
      <wsdl:input message="tns:echo" name="echo">
      </wsdl:input>
      <wsdl:output message="tns:echoResponse" name="echoResponse">
      </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RMServiceSoapBinding" type="tns:RMEndpoint">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="echo">
      <soap:operation soapAction="" style="rpc"/>
      <wsdl:input name="echo">
        <soap:body namespace="http://org.jboss.ws.jaxws.cxf/wsrm" use="literal"/>
      </wsdl:input>
      <wsdl:output name="echoResponse">
        <soap:body namespace="http://org.jboss.ws.jaxws.cxf/wsrm" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RMService">
    <wsdl:port binding="tns:RMServiceSoapBinding" name="RMEndpointPort">
      <soap:address location="http://@jboss.bind.address@:8080/jaxws-cxf-wsrm-basic-rpc"/>
      <wsp:PolicyReference URI="#RM" xmlns:wsp="http://www.w3.org/ns/ws-policy"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
