
== JBoss Modules

The JBoss Web Services functionalities are provided by a given set of
modules / libraries installed on the server.

On WildFly, those are organized into JBoss Modules modules. In
particular the _org.jboss.as.webservices.*_ and _org.jboss.ws.*_ modules
belong to the JBossWS - WildFly integration. Users should not need to
change anything in them.

While users are allowed to provide their own modules for their
custom needs, below is a brief collection of suggestions and hints
around modules and webservices development on WildFly.


=== Setting module dependencies

On WildFly the user deployment classloader does not have any visibility
over JBoss internals; so for instance you can't _directly_ use JBossWS
_implementation_ classes unless you explicitly set a dependency to the
corresponding module. As a consequence, users need to declare the module
dependencies they want to be added to their deployment.

[IMPORTANT]
====
The JBoss Web Services APIs are always available by default whenever the
webservices subsystem is available on AS7. Users just use them, no
need for explicit dependencies declaration for those modules.
====


==== Using MANIFEST.MF

The convenient method for configuring deployment dependencies is adding
them into the MANIFEST.MF file:

....
Manifest-Version: 1.0
Dependencies: org.jboss.ws.cxf.jbossws-cxf-client services export,foo.bar
....

Above _org.jboss.ws.cxf.jbossws-cxf-client_ and _foo.bar_ are the
modules you want to set dependencies to; _services_ tells the modules
framework that you want to import _META-INF/services/.._
declarations from the dependency, while _export_ exports the classes
from the module to any other module that might be depending on the
module implicitly created for your deployment.

[NOTE]
====
When using annotations on your endpoints / handlers such as the Apache
CXF ones (@InInterceptor, @GZIP, ...) remember to add the proper module
dependency in your manifest, otherwise your annotations are not picked
up and added to the annotation index by WildFly, resulting in them being
silently ignored.
====


===== Using JAXB

In order to directly use JAXB contexts, in your
client or endpoint running in-container, you need to properly setup a
JAXB implementation; that is performed setting the following dependency:

....
Dependencies: com.sun.xml.bind services export
....


===== Using Apache CXF

In order to use Apache CXF APIs and implementation classes you need
to add a dependency to the _org.apache.cxf_ (API) module and / or
_org.apache.cxf.impl_ (implementation) module:

....
Dependencies: org.apache.cxf services
....

Please note that that would not come with any JBossWS-CXF
customizations nor additional extensions. For this reason, and generally
speaking for simplifying user configuration, a client side aggregation
module is available with all the WS dependencies users might need.


===== Client side WS aggregation module

Whenever you want to use all the JBoss Web Services
feature/functionalities, you can set a dependency to the convenient
client module.

....
Dependencies: org.jboss.ws.cxf.jbossws-cxf-client services
....

Note the _services_ option above: it is strictly required in
order for you to get the JBossWS-CXF version of classes that are
retrieved using the _Service API_ , the `Bus` for instance.

[NOTE]
====
Be careful. Issues of misconfiguration here can be quite hard
to track down, because the Apache CXF behaviour would be sensibly
different.
====

[IMPORTANT]
====
The _services_ option is almost always needed when declaring
dependencies on _org.jboss.ws.cxf.jbossws-cxf-client_ and
_org.apache.cxf_ modules. It affects the
loading of classes through the _Service API_ , which is used to
wire most of the JBossWS components as well as all Apache CXF Bus
extensions.
====


===== Annotation scanning

The application server uses an annotation index for detecting JAX-WS
endpoints in the user deployments. When declaring WS endpoints, whose class
belongs to a different module (for instance referring that in the
`web.xml` descriptor), be sure to have an `annotations` type dependency
in place. Without that, your endpoints will be ignored as they
won't appear as annotated classes to the webservices subsystem.

....
Dependencies: org.foo annotations
....


==== Using jboss-deployment-descriptor.xml

In some circumstances, the convenient approach of setting module
dependencies in MANIFEST.MF might not work. An example is the need for
importing/exporting specific resources from a given module dependency.
Users should hence add a jboss-deployment-structure.xml descriptor to
their deployment and set module dependencies in it.
