
== Legal Notice

Copyright © 2011 Red Hat, Inc.

The text of and illustrations in this document are licensed by Red Hat
under a Creative Commons Attribution--Share Alike 3.0 Unported license
("CC-BY-SA"). An explanation of CC-BY-SA is available at
http://creativecommons.org/licenses/by-sa/3.0/[] . In accordance with
CC-BY-SA, if you distribute this document or an adaptation of it, you
must provide the URL for the original version.

Red Hat, as the licensor of this document, waives the right to enforce,
and agrees not to assert, Section 4d of CC-BY-SA to the fullest extent
permitted by applicable law.

Red Hat, Red Hat Enterprise Linux, the Shadowman logo, JBoss,
MetaMatrix, Fedora, the Infinity Logo, and RHCE are trademarks of Red
Hat, Inc., registered in the United States and other countries.

Linux® is the registered trademark of Linus Torvalds in the United
States and other countries.

Java® is a registered trademark of Oracle and/or its affiliates.

XFS® is a trademark of Silicon Graphics International Corp. or its
subsidiaries in the United States and/or other countries.

MySQL® is a registered trademark of MySQL AB in the United States, the
European Union and other countries.

Apache, Apache CXF, CXF, Apache WSS4J, WSS4J, Apache Maven, Maven and
the Apache feather logo are trademarks of The Apache Software
Foundation.

All other trademarks are the property of their respective owners.
