
package org.jboss.test.ws.jaxws.samples.wsa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.5-incubator
 * Mon Apr 21 16:36:02 CEST 2008
 * Generated source version: 2.0.5-incubator
 * 
 */

@XmlRootElement(name = "sayHello", namespace = "http://www.jboss.org/jbossws/ws-extensions/wsaddressing")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHello", namespace = "http://www.jboss.org/jbossws/ws-extensions/wsaddressing")

public class SayHello {


}

