= JBoss Modules

* <<anchor-1301,Setting module dependencies>>
** <<anchor-1302,Using MANIFEST.MF>>
*** <<anchor-1303,Using JAXB>>
*** <<anchor-1304,Using Apache CXF>>
*** <<anchor-1305,Client side WS aggregation module>>
*** <<anchor-1306,Annotation scanning>>
** <<anchor-1307,Using jboss-deployment-descriptor.xml>>

The JBoss Web Services functionalities are provided by a given set of modules / libraries installed on the server.

On WildFly, those are organized into JBoss Modules modules. In particular the org.jboss.as.webservices.* and org.jboss.ws.* modules belong to the JBossWS - WildFly integration. Users should not need to change anything in them.

While users are of course allowed to provide their own modules for their custom needs, below is a brief collection of suggestions and hints around modules and webservices development on WildFly.

[[anchor-1301]]
= Setting module dependencies

On WildFly the user deployment classloader does not have any visibility over JBoss internals; so for instance you can't directly use JBossWS implementation classes unless you explicitly set a dependency to the corresponding module. As a consequence, users need to declare the module dependencies they want to be added to their deployment.

====
TIP:

The JBoss Web Services APIs are always available by default whenever the webservices subsystem is available on AS7. So users just use them, no need for explicit dependencies declaration for those modules.
====

[[anchor-1302]]
= Using MANIFEST.MF

Here above org.jboss.ws.cxf.jbossws-cxf-client and foo.bar are the modules you want to set dependencies to; services tells the modules framework that you want to also import META-INF/services/.. declarations from the dependency, while export exports the classes from the module to any other module that might be depending on the module implicitly created for your deployment.

====
CAUTION:

When using annotations on your endpoints / handlers such as the Apache CXF ones (@InInterceptor, @GZIP, ...) remember to add the proper module dependency in your manifest. Otherwise your annotations are not picked up and added to the annotation index by WildFly, resulting in them being completely and silently ignored.
====

[[anchor-1303]]
= Using JAXB

In order for successfully directly using JAXB contexts, etc. in your client or endpoint running in-container, you need to properly setup a JAXB implementation; that is performed setting the following dependency:

----
Dependencies: com.sun.xml.bind services export
----

[[anchor-1304]]
= Using Apache CXF

In order for using Apache CXF APIs and implementation classes you need to add a dependency to the org.apache.cxf (API) module and / or org.apache.cxf.impl (implementation) module:

----
Dependencies: org.apache.cxf services
----

However, please note that would not come with any JBossWS-CXF customizations nor additional extensions. For this reason, and generally speaking for simplifying user configuration, a client side aggregation module is available with all the WS dependencies users might need.

[[anchor-1305]]
= Client side WS aggregation module

Whenever you simply want to use all the JBoss Web Services feature/functionalities, you can set a dependency to the convenient client module.

----
Dependencies: org.jboss.ws.cxf.jbossws-cxf-client services
----

Please note the services option above: that's strictly required in order for you to get the JBossWS-CXF version of classes that are retrieved using the Service API, the Bus for instance.

====
CAUTION:

Be careful as issues because of misconfiguration here can be quite hard to track down, because the Apache CXF behaviour would be sensibly different.
====

====
TIP:

The services option is almost always needed when declaring dependencies on org.jboss.ws.cxf.jbossws-cxf-client and org.apache.cxf modules. The reason for this is in it affecting the loading of classes through the Service API, which is what is used to wire most of the JBossWS components as well as all Apache CXF Bus extensions.
====

[[anchor-1306]]
= Annotation scanning

The application server uses an annotation index for detecting JAX-WS endpoints in user deployments. When declaring WS endpoints whose class belongs to a different module (for instance referring that in the web.xml descriptor), be sure to have an annotations type dependency in place. Without that, your endpoints would simply be ignored as they won't appear as annotated classes to the webservices subsystem.

----
Dependencies: org.foo annotations
----

[[anchor-1307]]
= Using jboss-deployment-descriptor.xml

In some circumstances, the convenient approach of setting module dependencies in MANIFEST.MF might not work. An example is the need for importing/exporting specific resources from a given module dependency. Users should hence add a jboss-deployment-structure.xml descriptor to their deployment and set module dependencies in it.
