
package org.jboss.test.ws.jaxws.samples.wsrm.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.5-incubator
 * Wed Apr 16 13:57:06 CEST 2008
 * Generated source version: 2.0.5-incubator
 * 
 */

@XmlRootElement(name = "echo", namespace = "http://www.jboss.org/jbossws/ws-extensions/wsrm")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "echo", namespace = "http://www.jboss.org/jbossws/ws-extensions/wsrm")

public class Echo {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }
    
    public void setArg0( java.lang.String newArg0 ) {
        this.arg0 = newArg0;
    }
    
}

