<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SaajService" targetNamespace="http://www.jboss.org/jbossws/saaj" xmlns:tns="http://www.jboss.org/jbossws/saaj" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.jboss.org/jbossws/saaj" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://www.jboss.org/jbossws/saaj">
      <xsd:element name="greetMe" type="tns:greetMe"/>
      <xsd:complexType name="greetMe">
        <xsd:sequence/>
      </xsd:complexType>
      <xsd:element name="greetMeResponse" type="tns:greetMeResponse"/>
      <xsd:complexType name="greetMeResponse">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="return" type="xsd:string"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="greetMeResponse">
    <wsdl:part name="parameters" element="tns:greetMeResponse"/>
  </wsdl:message>

  <wsdl:message name="greetMe">
    <wsdl:part name="parameters" element="tns:greetMe"/>
  </wsdl:message>

  <wsdl:portType name="ServiceIface">
    <wsdl:operation name="greetMe">
      <wsdl:input name="greetMe" message="tns:greetMe"/>
      <wsdl:output name="greetMeResponse" message="tns:greetMeResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="SaajServiceSoapBinding" type="tns:ServiceIface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/wsdl/http/"/>
    <wsdl:operation name="greetMe">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="greetMe">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="greetMeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="SaajService">
    <wsdl:port name="SaajServicePort" binding="tns:SaajServiceSoapBinding">
      <soap:address location="http://localhost:@add_int(port-offset.cxf-tests.jboss,8080)@/SaajService"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
