package org.jboss.test.ws.jaxws.cxf.interop.wstrust10.interopbaseaddress.interop;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2
 * Mon May 04 09:42:40 CEST 2009
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://InteropBaseAddress/interop", name = "IPingService")
@XmlSeeAlso({org.jboss.test.ws.jaxws.cxf.interop.wstrust10.org.xmlsoap.ping.ObjectFactory.class,ObjectFactory.class,org.jboss.test.ws.jaxws.cxf.interop.wstrust10.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class})
public interface IPingService {

    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://InteropBaseAddress/interop", className = "interopbaseaddress.interop.EchoResponse")
    @Action(input = "http://InteropBaseAddress/interop/echo", output = "http://InteropBaseAddress/interop/echo")
    @RequestWrapper(localName = "echo", targetNamespace = "http://InteropBaseAddress/interop", className = "interopbaseaddress.interop.Echo")
    @WebResult(name = "echoResult", targetNamespace = "http://InteropBaseAddress/interop")
    @WebMethod(action = "http://InteropBaseAddress/interop/echo")
    public java.lang.String echo(
        @WebParam(name = "request", targetNamespace = "http://InteropBaseAddress/interop")
        java.lang.String request
    );

    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://xmlsoap.org/Ping", className = "org.xmlsoap.ping.PingResponseBody")
    @Action(input = "http://xmlsoap.org/Ping", output = "http://xmlsoap.org/Ping")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://xmlsoap.org/Ping", className = "org.xmlsoap.ping.Ping")
    @WebMethod(operationName = "Ping", action = "http://xmlsoap.org/Ping")
    public void ping(
        @WebParam(mode = WebParam.Mode.INOUT, name = "scenario", targetNamespace = "http://xmlsoap.org/Ping")
        javax.xml.ws.Holder<java.lang.String> scenario,
        @WebParam(mode = WebParam.Mode.INOUT, name = "origin", targetNamespace = "http://xmlsoap.org/Ping")
        javax.xml.ws.Holder<java.lang.String> origin,
        @WebParam(mode = WebParam.Mode.INOUT, name = "text", targetNamespace = "http://xmlsoap.org/Ping")
        javax.xml.ws.Holder<java.lang.String> text
    );
}
